### ISSUE TITLE
Three minor bugs

### ISSUE THREAD

**Issue by inadarei** [round/TypeSmart-beta#4]
**Describe the bug**
Several bugs:

1. Previous PR broke "_A" and "_C" etc. in its attempt to implement case insensitivity
2. Typing of "2/2" and "1/3"  never worked
3. Technically it isn't a bug, but HOW DID YOU NOT IMPLEMENT a "shrug" replacement?

**Expected behavior**
The aforementioned three things working well

**Comment by round** [comment]
🤷‍♂

**Comment by round** [comment]
Question: "_A" "_c" etc. are *not* case insensitive – they have upper/lower case equivalents:

https://github.com/round/TypeSmart-beta/blob/41d2dd28593a018e43fe4cf65740ddc54b64e2db/content.js#L73-L87

I may be confused…

**Comment by inadarei** [comment]
Right, and that is what previous PR broke, unintentionally :) This PR restores the harmonious order of the matters where “_<letter>” replacements have proper upper and lower equivalents
