### ISSUE TITLE
What do these regexes do?

### ISSUE THREAD

**Issue by inadarei** [round/TypeSmart-beta#6]
Trying to understand what these regexes do and can’t figure it out. When removing them, everything still seems to be working, anyway?

```javascript
  .replace(new RegExp('(\\s|^|\\(|\\>|\\])(\")(?=[^>\\]]*(<|\\[|$))', 'g'), "$1“")
  .replace(new RegExp("(\\s|^|\\(|\\>|\\])(')(?=[^>\\]]*(<|\\[|$))", 'g'), "$1‘")
  .replace(new RegExp('(.)(\")(?=[^>\\]]*(<|\\[|$))', 'g'), "$1”")
  .replace(new RegExp("(.)(')(?=[^>\\]]*(<|\\[|$))", 'g'), "$1’")
```

**Comment by round** [comment]
These are the core directives that replace "dumb quotes" with ”smart quotes.”

https://github.com/round/TypeSmart-beta/blame/master/readme.md#L30
