### ISSUE TITLE
Space bar stops working

### ISSUE THREAD

**Issue by whale** [round/TypeSmart-beta#9]
**Describe the bug**
I am typing, backspacing, typing, then the space bar stops working. VERY scary ;)

**Expected behavior**
I expect the keyboard to work per normal other than the awesome little doodads that I expect from SmartType

**Screenshots**
https://cl.ly/99cf5b23c79f

**Comment by MarkyCDavis** [comment]
Confirmed this bug, github sucks and won’t let me upload a video so I’m texting it to you round.

**Comment by inadarei** [comment]
I believe this is duplicate of #7 and is fixed by PR f17d19fd79620d81ba60c19350e081743b6d12db
